### ISSUE TITLE
Closing a `Dispatcher` from within it seems to enter invalid state (?)

### ISSUE THREAD

**Issue by armanbilge** [typelevel/cats-effect#3501]
Consider this snippet.
```scala
//> using lib "org.typelevel::cats-effect::3.5.0-RC3"

import cats.effect._
import cats.effect.std.Dispatcher

import scala.concurrent.duration._

object App extends IOApp.Simple {
  // same result with sequential
  def run = Dispatcher.parallel[IO].allocated.flatMap {
    case (dispatcher, release) =>
      IO(dispatcher.unsafeRunAndForget(release)) *>
        IO.sleep(100.millis) *>
        IO(dispatcher.unsafeRunAndForget(IO.println("please don't print"))) *>
        IO.sleep(100.millis) *>
        IO.println("huh")
  }
}
```

What that's doing is starting a `Dispatcher`, and then attempting to close that dispatcher by submitting the close action to it.

When I tried this I wasn't entirely sure what to expect: `release` will block until the `Dispatcher` cancels all ongoing tasks. But one of those ongoing tasks is canceling the `Dispatcher`, which is blocked ... 🤔 so I thought this would either deadlock or the release would be `canceled`.

Well, it doesn't deadlock. But also the `Dispatcher` no long appears to work e.g. the `IO.println(...)` doesn't print. _But_ it still allows to submit tasks to it, instead of raising an `java.lang.IllegalStateException: dispatcher already shutdown`.

So it's in this weird state, where nothing is running but shutdown somehow hasn't completed.

**Comment by armanbilge** [comment]
Oh, nevermind. Just turns out that `100.millis` was not sufficient, which is surprising. `1000.millis` works. Maybe a cold JVM.

**Comment by armanbilge** [comment]
Actually, the `parallel` dispatcher is fine, but seems to be an issue still with `sequential` 🤔

**Comment by djspiewak** [comment]
@armanbilge Is this fixed now?

**Comment by samspills** [comment]
@djspiewak oh whoops, I said I would look at this 😅 I think this might have been resolved with the `alive` change in #3510, but I haven't written a proper test for it yet

**Comment by durban** [comment]
Something still doesn't seem okay with this: https://github.com/typelevel/cats-effect/actions/runs/4866933748/jobs/8678979906?pr=3592#step:23:4698

**Comment by samspills** [comment]
Thank you for reopening @durban!

I can replicate the flake easily with the following setup:

```scala
"issue 3501: reject new tasks after release action is submitted as a task" in real {
  dispatcher                                                                        
    .allocated                                                                      
    .flatMap {                                                                      
      case (runner, release) =>                                                     
        IO(runner.unsafeRunAndForget(release)) *>                                   
          IO(ok)                                                                    
      // IO.sleep(100.millis) *>                                                     
      // IO(runner.unsafeRunAndForget(IO(ko)) must throwAn[IllegalStateException])  
    }                                                                               
    .replicateA(2000)                                                               
}                                                                                   
```

The error is being raised on the first task, because the release is occasionally progressing fast enough that it fails its own submission 😅 This makes sense in retrospect and the fix is, I think, pretty straightforward (update that first action to sleep a little bit before the release starts). I can put up a PR tomorrow!

### update

So the thing is that the sequential dispatchers fail the way I expect: the double-check on `alive` within `unsafeToFutureCancelable` fails, because the release has started running and alive is false: great, perfect 👍🏻 

HOWEVER **parallel** dispatchers sometimes fail on the first check, before the task is even enqueued! Indeed I added some print statements and it seems like possibly `alive` is already false as soon as `unsafeToFutureToCancelable` starts. The fix to make the test stop flaking would remain the same, but I am trying to understand what is going on first. I'm sorry, hopefully it is not flaking too much :(
